version: '3'

networks:
    laravel_network:
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:8000"
#        volumes:
#            - .:/var/www/html
        environment:
            - APP_ENV=debug
#            - DB_CONNECTION=mysql
#            - DB_HOST=127.0.0.1
#            - DB_PORT=3306
#            - DB_DATABASE=danceshow
#            - DB_USERNAME=root
#            - DB_PASSWORD=br272745
